### ISSUE TITLE
Compile Error: require_once(): Failed opening required 

### ISSUE THREAD

**Issue by boybeak** [GoogleCloudPlatform/appengine-symfony-starter-project#2]
![屏幕快照 2015-11-15 下午3.23.56](http://ww2.sinaimg.cn/bmiddle/62da73f7gw1ey1oy682j4j21go0miagz.jpg)

```
error happened when run it on local computer
```

**Comment by bshaffer** [comment]
The application falls back to file cache when running locally, unless you are using Dev Appserver, in which case the `gs://` URL is valid.

The issue is probably that you have not created the bucket name you provided. Either that or this question is just way out-of-date and has long since been fixed.
